name: PDD Action

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  pdd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Build PDD Action
        run: |
          go build -o pdd-action ./cmd/pdd-action
      
      - name: Run PDD Action locally
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_NAME: "pull_request"
          GITHUB_WORKSPACE: ${{ github.workspace }}
          GITHUB_REF: ${{ github.ref }}
          PDD_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PDD_BRANCH_NAME: test-pdd-action
          PDD_ISSUE_PREFIX: "[PDD-TEST]"
        run: |
          ./pdd-action