name: Test PDD Action

on:
  workflow_dispatch:
  push:
    branches:
      - test-pdd-action
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  pdd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
          
      - name: Build action
        run: |
          go build -o pdd-action ./cmd/pdd-action
          
      - name: Debug info
        run: |
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
          echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
          echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "Token length: ${#GITHUB_TOKEN}"
        
      - name: Run PDD Action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PDD_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_NAME: "workflow_dispatch"
          GITHUB_WORKSPACE: ${{ github.workspace }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          PDD_BRANCH_NAME: test-pdd-action
          PDD_ISSUE_PREFIX: "[PDD]"
        run: |
          ./pdd-action