name: Test PDD Action

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  pdd:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
          
      - name: Build action
        run: |
          go build -o pdd-action ./cmd/pdd-action
          
      - name: Run PDD Action
        env:
          PDD_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PDD_BRANCH_NAME: test-pdd-action
          PDD_ISSUE_PREFIX: "[TEST-PDD]"
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
          GITHUB_EVENT_NAME: workflow_dispatch
        run: |
          ./pdd-action