name: Test PDD Action

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  pdd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run PDD Action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch_name: test-pdd-action
          issue_title_prefix: "[PDD]"